class movie:
    def __init__(self,moviejson):
        self.mvname = moviejson['mvname']
        self.url = moviejson['url']
        self.enname = moviejson['enname']
        #self.writer = moviejson['writer']
        self.director = moviejson['director']
        self.actors = moviejson['actors']
        self.types = moviejson['types']
        #self.areas = moviejson['areas']
        #self.lang = moviejson['lang']
        self.date = moviejson['date']
        #self.length = moviejson['length']
        self.imdblink = moviejson['imdblink']
        self.summary = moviejson['summary']
        #self.rank = moviejson['rank']
        #self.ranker = moviejson['ranker']
        #self.imdbrank = moviejson['imdbrank']
        #self.imdbranker = moviejson['imdbranker']
        #self.ratavg = moviejson['ratavg']